# Generated by Django 6.0.6 on 2026-06-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('supermercado', 'Supermercado'), ('farmacia', 'Farmacia'), ('ferreteria', 'Ferretería')], max_length=20)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_fin_destacado', models.DateField(blank=True, help_text='Si se deja vacío, el destacado no vence solo.', null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'ordering': ['provincia', 'nombre'],
                'unique_together': {('nombre', 'provincia')},
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='comercios.ciudad')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='comercios.comercio')),
            ],
            options={
                'verbose_name_plural': 'sucursales',
                'ordering': ['ciudad', 'nombre_sucursal'],
            },
        ),
    ]
