# Generated by Django 6.0.6 on 2026-06-28 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listacomparacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_comparacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcomparacion',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comparador.listacomparacion'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcomparacion',
            unique_together={('lista', 'producto')},
        ),
    ]
