# Generated by Django 6.0.6 on 2026-06-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_registrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='comercios.comercio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='catalogo.producto')),
            ],
            options={
                'verbose_name_plural': 'historial de precios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='comercios.comercio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto')),
            ],
            options={
                'ordering': ['producto', 'comercio'],
                'unique_together': {('producto', 'comercio')},
            },
        ),
    ]
